// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ServiceRegister.AcceptanceTests.Features.Organization
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class UpdatingOrganizationContactInformationFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "UpdatingOrganizationContactInformation.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "UpdatingOrganizationContactInformation", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "UpdatingOrganizationContactInformation")))
            {
                ServiceRegister.AcceptanceTests.Features.Organization.UpdatingOrganizationContactInformationFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line 4
 testRunner.Given("there is an organization", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Setting organization contact information")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UpdatingOrganizationContactInformation")]
        public virtual void SettingOrganizationContactInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Setting organization contact information", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phone number",
                        "Phone call fee",
                        "Email address",
                        "web site name",
                        "web address",
                        "web page type",
                        "second web site name",
                        "second web address",
                        "second web page type"});
            table1.AddRow(new string[] {
                        "0205 777 450",
                        "Local call cost",
                        "info.fi@affecto.com",
                        "Finnish site",
                        "www.affecto.fi",
                        "Kotisivu",
                        "Global site",
                        "www.affecto.com",
                        "Kotisivu"});
#line 7
 testRunner.When("the following contact information is set to the organization:", ((string)(null)), table1, "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phone number",
                        "Phone call fee",
                        "Email address",
                        "web site name",
                        "web address",
                        "web page type",
                        "second web site name",
                        "second web address",
                        "second web page type"});
            table2.AddRow(new string[] {
                        "0205 777 450",
                        "Local call cost",
                        "info.fi@affecto.com",
                        "Finnish site",
                        "www.affecto.fi",
                        "Kotisivu",
                        "Global site",
                        "www.affecto.com",
                        "Kotisivu"});
#line 10
 testRunner.Then("the organization has the following contact information:", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Setting organization contact information again")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UpdatingOrganizationContactInformation")]
        public virtual void SettingOrganizationContactInformationAgain()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Setting organization contact information again", ((string[])(null)));
#line 14
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phone number",
                        "Phone call fee",
                        "Email address",
                        "web site name",
                        "web address",
                        "web page type",
                        "second web site name",
                        "second web address",
                        "second web page type"});
            table3.AddRow(new string[] {
                        "0100100",
                        "Local call",
                        "info@affecto.com",
                        "Finland",
                        "www.affecto.fi",
                        "Kotisivu",
                        "Everyone",
                        "www.affecto.com",
                        "Kotisivu"});
#line 15
 testRunner.Given("the following contact information is set to the organization:", ((string)(null)), table3, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phone number",
                        "Phone call fee",
                        "Email address",
                        "web site name",
                        "web address",
                        "web page type",
                        "second web site name",
                        "second web address",
                        "second web page type"});
            table4.AddRow(new string[] {
                        "0205 777 450",
                        "Local call cost",
                        "info.fi@affecto.com",
                        "Finnish site",
                        "www.affecto.fi",
                        "Kotisivu",
                        "Global site",
                        "www.affecto.com",
                        "Kotisivu"});
#line 18
 testRunner.When("the following contact information is set to the organization:", ((string)(null)), table4, "When ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phone number",
                        "Phone call fee",
                        "Email address",
                        "web site name",
                        "web address",
                        "web page type",
                        "second web site name",
                        "second web address",
                        "second web page type"});
            table5.AddRow(new string[] {
                        "0205 777 450",
                        "Local call cost",
                        "info.fi@affecto.com",
                        "Finnish site",
                        "www.affecto.fi",
                        "Kotisivu",
                        "Global site",
                        "www.affecto.com",
                        "Kotisivu"});
#line 21
 testRunner.Then("the organization has the following contact information:", ((string)(null)), table5, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Organization can have no contact information")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UpdatingOrganizationContactInformation")]
        public virtual void OrganizationCanHaveNoContactInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Organization can have no contact information", ((string[])(null)));
#line 25
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phone number",
                        "Phone call fee",
                        "Email address",
                        "web site name",
                        "web address",
                        "web page type",
                        "second web site name",
                        "second web address",
                        "second web page type"});
            table6.AddRow(new string[] {
                        "0100100",
                        "Local call",
                        "info@affecto.com",
                        "Finland",
                        "www.affecto.fi",
                        "Kotisivu",
                        "Everyone",
                        "www.affecto.com",
                        "Kotisivu"});
#line 26
 testRunner.Given("the following contact information is set to the organization:", ((string)(null)), table6, "Given ");
#line 29
 testRunner.When("contact information of the organization is set as empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
 testRunner.Then("the organization has no contact information", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Setting invalid email address")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UpdatingOrganizationContactInformation")]
        public virtual void SettingInvalidEmailAddress()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Setting invalid email address", ((string[])(null)));
#line 32
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phone number",
                        "Phone call fee",
                        "Email address",
                        "web site name",
                        "web address",
                        "web page type",
                        "second web site name",
                        "second web address",
                        "second web page type"});
            table7.AddRow(new string[] {
                        "0205 777 450",
                        "Local call cost",
                        "info.fi2affecto.com",
                        "Finnish site",
                        "www.affecto.fi",
                        "Kotisivu",
                        "Global site",
                        "www.affecto.com",
                        "Kotisivu"});
#line 33
 testRunner.When("the following contact information is set to the organization:", ((string)(null)), table7, "When ");
#line 36
 testRunner.Then("setting the contact information fails", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Setting invalid phone number")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UpdatingOrganizationContactInformation")]
        public virtual void SettingInvalidPhoneNumber()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Setting invalid phone number", ((string[])(null)));
#line 38
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phone number",
                        "Phone call fee",
                        "Email address",
                        "web site name",
                        "web address",
                        "web page type",
                        "second web site name",
                        "second web address",
                        "second web page type"});
            table8.AddRow(new string[] {
                        "Local call cost",
                        "Local call cost",
                        "info.fi@affecto.com",
                        "Finnish site",
                        "www.affecto.fi",
                        "Kotisivu",
                        "Global site",
                        "www.affecto.com",
                        "Kotisivu"});
#line 39
 testRunner.When("the following contact information is set to the organization:", ((string)(null)), table8, "When ");
#line 42
 testRunner.Then("setting the contact information fails", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Setting invalid web address")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UpdatingOrganizationContactInformation")]
        public virtual void SettingInvalidWebAddress()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Setting invalid web address", ((string[])(null)));
#line 44
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phone number",
                        "Phone call fee",
                        "Email address",
                        "web site name",
                        "web address",
                        "web page type",
                        "second web site name",
                        "second web address",
                        "second web page type"});
            table9.AddRow(new string[] {
                        "0205 777 450",
                        "Local call cost",
                        "info.fi@affecto.com",
                        "Finnish site",
                        "www.affecto.fi",
                        "Kotisivu",
                        "Global site",
                        "www,affecto,com",
                        "Kotisivu"});
#line 45
 testRunner.When("the following contact information is set to the organization:", ((string)(null)), table9, "When ");
#line 48
 testRunner.Then("setting the contact information fails", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
