// <auto-generated />
namespace ServiceRegister.Store.CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ShorterServiceNames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ShorterServiceNames));
        
        string IMigrationMetadata.Id
        {
            get { return "201511111149342_ShorterServiceNames"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
